/** Declaration file generated by dts-gen */

export = koa_lusca;

declare function koa_lusca(options: any): any;

declare namespace koa_lusca {
    function csp(options: any): any;

    function csrf(options: any): any;

    function cto(options: any): any;

    function hsts(options: any): any;

    function p3p(options: any): any;

    function xframe(options: any): any;

    function xssProtection(options: any): any;

}

